#!/bin/bash

usage () {
  echo "Usage: "
  echo "del [controller,middleware,model,helper] NAME"
  echo ""
}

controller () {
  name="$1"
  to_del="${name}Controller"
  if [ -e "app/controllers/$to_del" ]; then
    rm -rf app/controllers/$to_del
    echo ""
    echo "$(tput setaf 3)removed $to_del $(tput sgr0)"
    echo ""
  else
    echo ""
    echo "$(tput setaf 1)$to_del does not exist. Cannot delete $(tput sgr0)"
    echo ""
  fi
}

middleware () {
  name="$1"
  if [ -e "app/middleware/$name" ]; then
    rm -rf app/middleware/$name
    echo ""
    echo "$(tput setaf 3)removed ${name}Middleware $(tput sgr0)"
    echo ""
  else
    echo ""
    echo "$(tput setaf 1)${name}Middleware does not exist. Cannot delete $(tput sgr0)"
    echo ""
  fi
}

helper () {
  name="$1"
  to_del="${name}Helper"
  if [ -e "app/helpers/$to_del" ]; then
    rm -rf app/helpers/$to_del
    echo ""
    echo "$(tput setaf 3)removed $to_del $(tput sgr0)"
    echo ""
  else
    echo ""
    echo "$(tput setaf 1)$to_del does not exist. Cannot delete $(tput sgr0)"
    echo ""
  fi
}

model () {
  name="$1"
  to_del="${name}"
  if [ -e "app/models/$to_del" ]; then
    rm -rf app/models/$to_del
    echo ""
    echo "$(tput setaf 3)removed $to_del $(tput sgr0)"
    echo ""
  else
    echo ""
    echo "$(tput setaf 1)$to_del does not exist. Cannot delete $(tput sgr0)"
    echo ""
  fi
}

if [ "$#" -lt 2 ]; then
  usage
  exit 1
fi

case "$1" in
  "controller")
    controller "$2"
    exit 1
    ;;
  "middleware")
    middleware "$2"
    exit 1
    ;;
  "helper")
    helper "$2"
    exit 1
    ;;
  "model")
    model "$2"
    exit 1
    ;;
  *)
    usage
    exit 1
    ;;
esac
