#!/bin/bash

usage () {
  echo "Usage: "
  echo "gen [controller,middleware] NAME"
  echo ""
}

controller () {
  name="$1"
  to_write="${name}Controller"
  if [[ ! -e "app/controllers/$to_write" ]]; then
    file="$(cat ./templates/controller.js)"
    result="${file//CONTROLLER/$to_write}"
    result="${result//URL/$name}"
    mkdir app/controllers/$to_write
    echo "$result" > app/controllers/$to_write/index.js
    echo ""
    echo "$(tput setaf 2)$to_write generated in app/controllers/$to_write $(tput sgr0)"
    echo ""
  else
    echo ""
    echo "$(tput setaf 1)$to_write already exists $(tput sgr0)"
    echo ""
  fi
}

middleware () {
  name="$1"
  to_write="${name}Middleware"
  if [[ ! -e "app/middleware/$name" ]]; then
    file="$(cat ./templates/middleware.js)"
    result="${file//MIDDLEWARE/$to_write}"
    mkdir app/middleware/$name
    echo "$result" > app/middleware/$name/index.js
    echo ""
    echo "$(tput setaf 2)$to_write generated in app/middleware/$name $(tput sgr0)"
    echo ""
  else
    echo ""
    echo "$(tput setaf 1)$to_write already exists $(tput sgr0)"
    echo ""
  fi
}

helper () {
  name="$1"
  to_write="${name}Helper"
  if [[ ! -e "app/helpers/$to_write" ]]; then
    file="$(cat ./templates/helper.js)"
    result="${file//HELPER/$to_write}"
    mkdir app/helpers/$to_write
    echo "$result" > app/helpers/$to_write/index.js
    echo ""
    echo "$(tput setaf 2)$to_write generated in app/helpers/$to_write $(tput sgr0)"
    echo ""
  else
    echo ""
    echo "$(tput setaf 1)$to_write already exists $(tput sgr0)"
    echo ""
  fi
}

model () {
  name="$1"
  to_write="${name}"
  if [[ ! -e "app/models/$to_write" ]]; then
    file="$(cat ./templates/model.js)"
    result="${file//MODEL/$to_write}"
    mkdir app/models/$to_write
    echo "$result" > app/models/$to_write/index.js
    echo ""
    echo "$(tput setaf 2)${to_write}Model generated in app/models/$to_write $(tput sgr0)"
    echo ""
  else
    echo ""
    echo "$(tput setaf 1)$to_write already exists $(tput sgr0)"
    echo ""
  fi
}

if [ "$#" -lt 2 ]; then
  usage
  exit 1
fi

case "$1" in
  "controller")
    controller "$2"
    exit 1
    ;;
  "middleware")
    middleware "$2"
    exit 1
    ;;
  "helper")
    helper "$2"
    exit 1
    ;;
  "model")
    model "$2"
    exit 1
    ;;
  *)
    usage
    exit 1
    ;;
esac
