#!/bin/bash

usage () {
  echo "Usage: "
  echo "gen controller CONTROLLER_NAME"
  echo ""
}

controller () {
  name="$1"
  to_write="${name}Controller"
  if [[ ! -e "app/controllers/$to_write" ]]; then
    file="$(cat ./templates/controller.js)"
    result="${file//CONTROLLER/$to_write}"
    result="${result//URL/$name}"
    mkdir app/controllers/$to_write
    echo "$result" > app/controllers/$to_write/index.js
    echo ""
    echo "$(tput setaf 2)$to_write generated in app/controllers/$to_write $(tput sgr0)"
    echo ""
  else
    echo ""
    echo "$(tput setaf 1)$to_write already exists $(tput sgr0)"
    echo ""
  fi
}

if [ "$#" -lt 2 ]; then
  usage
  exit 1
fi

case "$1" in
  "controller")
    controller "$2"
    exit 1
    ;;
  *)
    usage
    exit 1
    ;;
esac
